### ISSUE TITLE
Add Brad

### ISSUE THREAD

**Issue by bpasanek** [walshbr/gradconworkshop#1]
Dear Brandon, could you add me (bpasanek) as a contributor? I'll post materials here.

**Comment by walshbr** [comment]
Done! Let me know if it didn't take @bpasanek

**Comment by bpasanek** [comment]
﻿It took!

*****************************************
Brad Pasanek (he/him)
Mayo NEH Distinguished Teaching Professor
U.Va. English Department
–––––––––––––––––––––––––––––––––––
